VinTwitta/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = "vintwitta"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^djangojs/', include('djangojs.urls')),

    url(r'^$', TemplateView.as_view(template_name='tweet_monitor/index.html'), name='home'),
    url(r"^tweets/", include("tweet_monitor.urls"), name="tweets"),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

tweet_monitor/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = "tweet_monitor"

urlpatterns = [
    # React view
    url(r'^process_add_handle/$', views.add_handle, name='add_handle'),
    # url(r'^$', TemplateView.as_view(template_name='tweet_monitor/react_index.html'), name='index'),
    url(r'^$', views.index, name='index'),

    # Pure Django views
    # url(r'^/$', views.index, name='index2'),
    # url(r'^list/$', views.TweetsView.as_view(), name='tweets_list'),
    # url(r'^add_handle/$', views.add_handle, name='add_handle'),
    # url(r'^filters/$', views.filters, name='filters'),
    # url(r'^process_filter/$', views.process_filter, name='process_filter'),

    # DRF views
    url(r'^filters/user/(?P<username>\S+)/$', views.UserTweetsView.as_view(), name='tweets_by_username'),
    url(r'^filters/date/(?P<date>.+)/$', views.DateRangeTweetsView.as_view(), name='tweets_by_date'),
    url(r'^filters/text/(?P<text>\S+)/$', views.TextTweetsView.as_view(), name='tweets_by_text'),
    url(r'^filters/hashtag/(?P<hashtag>\S+)/$', views.HashtagTweetsView.as_view(), name='tweets_by_hashtag'),
    url(r'^list_hashtags/$', views.HashtagsView.as_view(), name='hashtags_list'),

    url(r'^fetch/$', views.FetchTweetsView.as_view(), name='fetch_tweets'),

    url(r'^.*/', TemplateView.as_view(template_name="tweet_monitor/react_index.html"), name='react_base'),
]

tweet_monitor/models.py
from django.db import models


class Hashtag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Tweet(models.Model):
    provider_id = models.CharField(max_length=30, unique=True)
    text = models.CharField(max_length=150)
    owner = models.CharField(max_length=50)
    creation_date = models.DateTimeField()
    hashtags = models.ManyToManyField(Hashtag)

    def extract_hashtags(self):
        words = self.text.split()
        temp_list = [word for word in words if word[0] == "#"]

        for ht in temp_list:
            obj, created = Hashtag.objects.get_or_create(name=ht)
            self.hashtags.add(obj)

    def __str__(self):
        return "@{}: {} at {}".format(self.owner, self.text, self.creation_date)

tweet_monitor/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from social_django.models import UserSocialAuth
import tweepy
from tweepy import TweepError

from .models import Tweet, Hashtag
from .serializers import TweetSerializer, HashtagSerializer


# ########### Retrieval Endpoints ########### #


class TweetsView(generics.ListAPIView):
    """ Returns a list of all tweets. """
    model = Tweet
    serializer_class = TweetSerializer

    def get_queryset(self):
        return Tweet.objects.all()


class UserTweetsView(generics.ListAPIView):
    """ Returns a list of all tweets from a specific user. """
    model = Tweet
    serializer_class = TweetSerializer

    def get_queryset(self):
        if self.kwargs.get('username'):
            return Tweet.objects.filter(owner__iexact=self.kwargs.get('username'))


class DateRangeTweetsView(generics.ListAPIView):
    """ Returns a list of all tweets in a specific date range. """
    model = Tweet
    serializer_class = TweetSerializer

    def get_queryset(self):
        if self.kwargs.get('date'):
            return Tweet.objects.filter(creation_date__gte=self.kwargs.get('date'))


class TextTweetsView(generics.ListAPIView):
    """ Returns a list of all tweets containing a specific text. """
    model = Tweet
    serializer_class = TweetSerializer

    def get_queryset(self):
        if self.kwargs.get('text'):
            return Tweet.objects.filter(text__icontains=self.kwargs.get('text'))


class HashtagsView(generics.ListAPIView):
    """ Returns a list of all hashtags. """
    model = Hashtag
    serializer_class = HashtagSerializer

    def get_queryset(self):
        return Hashtag.objects.all()


class HashtagTweetsView(generics.ListAPIView):
    """ Returns a list of all tweets containing a specific hashtag. """
    model = Tweet
    serializer_class = TweetSerializer

    def get_queryset(self):
        hashtag = self.kwargs.get('hashtag')
        if hashtag:
            hashtag = "#" + hashtag if hashtag[0] != "#" else hashtag
            return Tweet.objects.filter(Q(hashtags__name__iexact=hashtag))


# ########### Creation Endpoints ########### #
class FetchTweetsView(APIView):
    """ Fetches 200 most recent tweets from a specific user and stores them in the DB. """

    def post(self, request):
        username = request.data.get('username')
        if username:
            response = _add_handle(request.data.get("user_id"), username)
        else:
            response = "Please provide a Twitter handle to have its tweets fetched."

        return Response(response)


def _add_handle(user_id, handle):

    found = Tweet.objects.filter(owner__iexact=handle)
    if found:
        return_message = "The handle {} was already added to the database!".format(handle)
    else:
        user_obj = UserSocialAuth.objects.get(user_id=user_id)
        tweepy_handler = generate_tweepy_handler(user_obj.extra_data['access_token']['oauth_token'],
                                                 user_obj.extra_data['access_token']['oauth_token_secret'])

        try:
            statuses = tweepy_handler.user_timeline(screen_name=handle, count=200)
            tweets_list = []

            for status in statuses:
                tweet = Tweet(provider_id=status.id, owner=status.user.screen_name, text=status.text,
                              creation_date=status.created_at)
                tweets_list.append(tweet)

            Tweet.objects.bulk_create(tweets_list)

            saved_tweets = Tweet.objects.filter(owner__iexact=handle)
            for t in saved_tweets:
                t.extract_hashtags()

            return_message = "The handle {} was added!".format(handle)
        except TweepError as err:
            if err.response.status_code == 404:
                return_message = "The provided Twitter handle doesn't exist. Please check the spelling."
            else:
                return_message = "There was a problem in the request, please check the handle spelling and try again."

    return return_message


def generate_tweepy_handler(user_access_token, user_access_token_secret):
    """
    Generate handler object to use Tweepy's methods.
    :param user_access_token: The access token obtained from the signin process.
    :param user_access_token_secret: The access token secret.
    :return: The API handler.
    """
    consumer_key = settings.SOCIAL_AUTH_TWITTER_KEY
    consumer_secret = settings.SOCIAL_AUTH_TWITTER_SECRET
    access_key = user_access_token
    access_secret = user_access_token_secret
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    handler = tweepy.API(auth)

    return handler


@login_required
def index(request):
    payload = {
        "name": request.user.first_name,
        "local_storage": {
            "sessionid": request.COOKIES.get("sessionid"),
            "csrftoken": request.COOKIES.get("csrftoken")
        }
    }

    return render(request, "tweet_monitor/react_index.html", payload)


@login_required
def add_handle(request):
    """
    Gets the user inserted Twitter handle and fetches his/her 200 more recent tweets, storing them in the DB.
    :param request: The HTTP request.
    :return: Redirects back to index view with the result message.
    """
    if request.POST:
        handle = request.POST.get("handleName")

        if handle:
            found = Tweet.objects.filter(owner__iexact=handle)
            if found:
                messages.warning(request, "{}' tweets were already in the database!".format(handle))
            else:
                user_obj = UserSocialAuth.objects.get(user_id=request.user.id)
                tweepy_handler = generate_tweepy_handler(user_obj.extra_data['access_token']['oauth_token'],
                                                         user_obj.extra_data['access_token']['oauth_token_secret'])

                try:
                    statuses = tweepy_handler.user_timeline(screen_name=handle, count=200)
                    tweets_list = []

                    for status in statuses:
                        tweet = Tweet(provider_id=status.id, owner=status.user.screen_name, text=status.text,
                                      creation_date=status.created_at)
                        tweets_list.append(tweet)

                    Tweet.objects.bulk_create(tweets_list)

                    saved_tweets = Tweet.objects.filter(owner__iexact=handle)
                    for t in saved_tweets:
                        t.extract_hashtags()

                    messages.success(request, "@{}'s tweets were added successfully!".format(handle))
                except TweepError as err:
                    print(":::: ERROR:", err, err.response.status_code)
                    if err.response.status_code == 404:
                        messages.error(request, "The provided Twitter handle doesn't exist. Please check the spelling.")
                    elif err.response.status_code == 401:
                        messages.error(request, "{}'s timeline is protected, we can't fetch his/her "
                                                "tweets.".format(handle))
                    else:
                        messages.error(request, "There was a problem in the request, please check the handle spelling "
                                                "and try again.")
        else:
            messages.error(request, "Please provide a Twitter handle to have its tweets fetched.")
    else:
        messages.error(request, "There was a problem in the request, please try again.")

    return HttpResponseRedirect(reverse("tweet_monitor:index"))


# ################### FOR TESTING PURPOSES ONLY ################### #

@login_required
def filters(request):
    hashtags = Hashtag.objects.all()
    return render(request, "tweet_monitor/filters.html", {"name": request.user.first_name, "hashtags": hashtags})


@login_required
def process_filter(request):
    if request.POST:
        if request.POST.get("userFilter"):
            print("User:", request.POST.get("userFilter"))
            tweets = Tweet.objects.filter(owner__iexact=request.POST.get("userFilter"))
        elif request.POST.get("dateFilter"):
            print("Date:", request.POST.get("dateFilter"))
        elif request.POST.get("textFilter"):
            print("Text:", request.POST.get("textFilter"))
            tweets = Tweet.objects.filter(text__icontains=request.POST.get("textFilter"))
        elif request.POST.get("hashtagFilter"):
            print("Hashtag:", request.POST.get("hashtagFilter"))
            tweets = Tweet.objects.filter(Q(hashtags__name__iexact=request.POST.get("hashtagFilter")))
            print("Tweets found:", tweets)
    else:
        messages.error(request, "There was a problem in the request, please try again.")

    hashtags = Hashtag.objects.all()
    return render(request, "tweet_monitor/filters.html", {"name": request.user.first_name, "hashtags": hashtags,
                                                          "tweets": tweets})

tweet_monitor/templates/tweet_monitor/filters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Filter Tweets | VinTwitta - Your Twitter Monitor</title>
  <script type="text/javascript">
    var hideAllFilters = function() {
      var fields = document.getElementsByClassName("filterField");

      for (var i = 0; i < fields.length; i++) {
        fields[i].style.display = "none";
      }
    };

    var changeFilter = function(type) {
      hideAllFilters();
      document.getElementsByName(type + "FilterDiv")[0].style.display = "block";
    }
  </script>
</head>
<body>
{% include "./header.html" %}
<p>Welcome, {{ name }}!</p>
<form method="POST" action="{% url 'tweet_monitor:process_filter' %}">
  {% csrf_token %}
  <p>Filter by:</p>
  <input type="radio" name="filterType" value="user" onchange="changeFilter('user')" /> User
  <input type="radio" name="filterType" value="date" onchange="changeFilter('date')" /> Date
  <input type="radio" name="filterType" value="text" onchange="changeFilter('text')" /> Text
  <input type="radio" name="filterType" value="hashtag" onchange="changeFilter('hashtag')" /> Hashtag
  <br/>
  <div class="filterField" name="userFilterDiv" style="display:none" >Username: <input type="text" name="userFilter" /></div>
  <div class="filterField" name="dateFilterDiv" style="display:none" >Date: <input type="text" name="dateFilter" /></div>
  <div class="filterField" name="textFilterDiv" style="display:none" >Text: <input type="text" name="textFilter" /></div>
  <div class="filterField" name="hashtagFilterDiv" style="display:none" >
    Hashtag: <select name="hashtagFilter">
              {% for hashtag in hashtags %}
                <option name="{{hashtag.id}}" >{{hashtag.name}}</option>
              {% endfor %}
            </select>
  </div>
  <br/>
  <input type="submit" value="FILTER!" />
</form>
<br />
<select style="min-width:300px" name="filteredTweets" size="10">
  {% for tweet in tweets %}
    <option name="{{tweet.id}}">{{tweet.text}}</option>
  {% endfor %}
</select>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</body>
</html>

tweet_monitor/templates/tweet_monitor/header.html
{% block header %}
[<a href="{% url 'tweet_monitor:index' %}">Tweets</a>] - [<a href="{% url 'tweet_monitor:filters' %}">Filters</a>]
{% endblock %}

tweet_monitor/templates/tweet_monitor/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home | VinTwitta - Your Twitter Monitor</title>
</head>
<body>
{% include "./header.html" %}
<p>Welcome, {{ name }}!</p>
<form method="POST" action="{% url 'tweet_monitor:add_handle' %}">
  {% csrf_token %}
  <input type="text" name="handleName" placeholder="Write a Twitter handle here." />
  <input type="submit" value="Fetch Tweets!" />
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</body>
</html>